Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    swapoff -a

    apt update && apt install -y elixir erlang-dev

    apt update
    apt install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt update
    apt install -y docker-ce
    usermod -aG docker vagrant

    # Add -H tcp://0.0.0.0 to /lib/systemd/system/docker.service
    # to expose the Docker daemon on TCP port 2375 publicly.
    sed -i 's|ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock|ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0 --containerd=/run/containerd/containerd.sock|' /lib/systemd/system/docker.service
    systemctl daemon-reload
    systemctl restart docker
  SHELL

  config.vm.define "elixir", primary: true do |elixir|
    elixir.vm.hostname = "elixir"
    elixir.vm.network "public_network", ip: "192.168.0.1"
  end

  config.vm.define "docker" do |docker|
    docker.vm.hostname = "docker"
    docker.vm.network "public_network", ip: "192.168.0.2"
  end
end
